export const UPDATE_CORRECT_STROKES = "UPDATE_CORRECT_STROKES"
export const UPDATE_MISTAKE_STROKES = "UPDATE_MISTAKE_STROKES"
export const UPDATE_CORRECT_CHAR = "UPDATE_CORRECT_CHAR"
export const UPDATE_PRECISION = "UPDATE_PRECISION"