name: deploy-main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: |
        npm install -g gatsby-cli
        npm install -g surge
    - name: Deploy on Surge
      env:
          CI: false # CRA treats warnings as errors in CI - re-enable if needed
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: |
        gatsby build
        surge public/ --domain https://learn-chinese-characters.surge.sh
